[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/personal-finance-manager-1.0.0.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
JAVA_VERSION = "17" 